/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dk_carolus_zpp_nativelib_ZppImage */

#ifndef _Included_dk_carolus_zpp_nativelib_ZppImage
#define _Included_dk_carolus_zpp_nativelib_ZppImage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dk_carolus_zpp_nativelib_ZppImage
 * Method:    zppNewImage
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_dk_carolus_zpp_nativelib_ZppImage_zppNewImage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     dk_carolus_zpp_nativelib_ZppImage
 * Method:    zppDestroyImage
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dk_carolus_zpp_nativelib_ZppImage_zppDestroyImage
  (JNIEnv *, jobject, jlong);

/*
 * Class:     dk_carolus_zpp_nativelib_ZppImage
 * Method:    zppFetchImageProperties
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dk_carolus_zpp_nativelib_ZppImage_zppFetchImageProperties
  (JNIEnv *, jobject, jlong);

/*
 * Class:     dk_carolus_zpp_nativelib_ZppImage
 * Method:    zppFetchTile
 * Signature: (JILjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_dk_carolus_zpp_nativelib_ZppImage_zppFetchTile
  (JNIEnv *, jobject, jlong, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
